# Generated by Django 3.2.13 on 2022-06-16 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="status",
            field=models.CharField(
                choices=[
                    ("actual", "Actual"),
                    ("canceled", "Отменена водителем"),
                    ("fully", "Полная посадка"),
                    ("finished", "Завершена"),
                ],
                default="actual",
                max_length=16,
                verbose_name="Status",
            ),
        ),
    ]
