# Generated by Django 3.2.13 on 2022-06-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0002_alter_trip_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="payment",
            field=models.CharField(
                choices=[("free", "Бесплатно"), ("pay", "Платно"), ("petrol", "Бензин")],
                default="free",
                max_length=16,
                verbose_name="Оплата",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="status",
            field=models.CharField(
                choices=[
                    ("actual", "Актуально"),
                    ("canceled", "Отменена водителем"),
                    ("fully", "Полная посадка"),
                    ("finished", "Завершена"),
                ],
                default="actual",
                max_length=16,
                verbose_name="Status",
            ),
        ),
    ]
