version: "3.3"
services:
  blabla_bot_pg:
    image: postgres:latest
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - blabla_bot_pg:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass

  blabla_bot_redis:
    image: redis
    restart: always
    ports:
      - "127.0.0.1:6379:6379"

volumes:
  blabla_bot_pg:
  blabla_bot_media:
  blabla_bot_static:
