# Generated by Django 3.2.13 on 2022-06-16 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bottextsconfig",
            name="publish_count_exceed",
            field=models.TextField(default="", verbose_name="Текст превышено кол-во в день"),
        ),
        migrations.AddField(
            model_name="bottextsconfig",
            name="text_trip",
            field=models.TextField(default="", verbose_name="Текст поездки в канале"),
        ),
        migrations.AlterField(
            model_name="botmainconfig",
            name="channel_name",
            field=models.CharField(
                default="",
                help_text="Для публикации поездок. Без @",
                max_length=64,
                verbose_name="Имя канала или группы",
            ),
        ),
    ]
