# Generated by Django 3.2.13 on 2022-06-16 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0003_auto_20220616_0035"),
    ]

    operations = [
        migrations.AddField(
            model_name="bottextsconfig",
            name="common_for_new_user_text",
            field=models.TextField(default="Привет новый юзер", verbose_name="Привет новый юзер"),
        ),
    ]
