# Generated by Django 3.2.13 on 2022-06-16 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0005_bottextsconfig_common_start"),
    ]

    operations = [
        migrations.AddField(
            model_name="bottextsconfig",
            name="button_new_trip",
            field=models.CharField(default="Создать поездку", max_length=128, verbose_name="Создать поездку"),
        ),
    ]
