# Generated by Django 3.2.13 on 2022-06-16 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0006_bottextsconfig_button_new_trip"),
    ]

    operations = [
        migrations.AddField(
            model_name="bottextsconfig",
            name="button_help",
            field=models.CharField(default="Помощь", max_length=128, verbose_name="Помощь"),
        ),
    ]
