# Generated by Django 3.2.13 on 2022-06-16 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0007_bottextsconfig_button_help"),
    ]

    operations = [
        migrations.AddField(
            model_name="bottextsconfig",
            name="new_trip_city_not_found",
            field=models.TextField(default="Город не найден", verbose_name="Город не найден"),
        ),
        migrations.AddField(
            model_name="bottextsconfig",
            name="new_trip_select_city_to",
            field=models.TextField(default="Выбьерите город в", verbose_name="Выбьерите город в"),
        ),
    ]
