# Generated by Django 3.2.13 on 2022-06-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0008_auto_20220616_0047"),
    ]

    operations = [
        migrations.AddField(
            model_name="bottextsconfig",
            name="new_trip_select_date",
            field=models.TextField(default="Выбьерите дату поездки", verbose_name="Выбьерите дату поездки"),
        ),
    ]
