# Generated by Django 3.2.13 on 2022-06-16 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0011_bottextsconfig_new_trip_select_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="bottextsconfig",
            name="new_trip_select_pass_count",
            field=models.TextField(default="Выбьерите кол-во пассажиров", verbose_name="Выбьерите кол-во пассажиров"),
        ),
    ]
