# Generated by Django 3.2.13 on 2022-06-16 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0014_bottextsconfig_new_ad_confirmed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bottextsconfig",
            name="new_ad_confirmed",
        ),
        migrations.AddField(
            model_name="bottextsconfig",
            name="new_trip_confirmed",
            field=models.TextField(default="Вы создали поездку", verbose_name="Вы создали поездку"),
        ),
    ]
