# Generated by Django 3.2.13 on 2022-06-16 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0015_auto_20220616_0139"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bottextsconfig",
            name="new_trip_confirm_no",
            field=models.TextField(default="Нет (перезаполнить)", verbose_name="Нет (перезаполнить)"),
        ),
        migrations.AlterField(
            model_name="bottextsconfig",
            name="new_trip_confirm_yes",
            field=models.TextField(default="Да (публикуем)", verbose_name="Да (публикуем)"),
        ),
    ]
