# Generated by Django 3.2.13 on 2022-06-16 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0016_auto_20220616_0142"),
    ]

    operations = [
        migrations.AddField(
            model_name="bottextsconfig",
            name="button_find_trip",
            field=models.CharField(default="Найти машину", max_length=128, verbose_name="Найти машину"),
        ),
        migrations.AddField(
            model_name="bottextsconfig",
            name="button_my_trips",
            field=models.CharField(default="Мои поездки", max_length=128, verbose_name="Мои поездки"),
        ),
    ]
