# Generated by Django 3.2.13 on 2022-06-16 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0017_auto_20220616_0156"),
    ]

    operations = [
        migrations.AddField(
            model_name="bottextsconfig",
            name="trip_list_one",
            field=models.TextField(
                default="Одно обхявление в моем списке", verbose_name="Одно обхявление в моем списке"
            ),
        ),
    ]
