# Generated by Django 3.2.13 on 2022-06-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0018_bottextsconfig_trip_list_one"),
    ]

    operations = [
        migrations.AddField(
            model_name="bottextsconfig",
            name="trip_not_found",
            field=models.TextField(default="Поездка не найдена", verbose_name="Поездка не найдена"),
        ),
    ]
