# Generated by Django 3.2.13 on 2022-06-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0020_auto_20220616_0609"),
    ]

    operations = [
        migrations.AddField(
            model_name="bottextsconfig",
            name="common_help_text",
            field=models.TextField(default="Текст помощи", verbose_name="Текст помощи"),
        ),
    ]
