# Generated by Django 3.2.13 on 2022-06-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0021_bottextsconfig_common_help_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="bottextsconfig",
            name="button_actual",
            field=models.CharField(default="🟢 Актуально", max_length=128, verbose_name="🟢 Актуально"),
        ),
        migrations.AddField(
            model_name="bottextsconfig",
            name="button_cancel",
            field=models.CharField(default="⛔ Отменить", max_length=128, verbose_name="⛔ Отменить"),
        ),
        migrations.AddField(
            model_name="bottextsconfig",
            name="button_fully",
            field=models.CharField(
                default="🙅\u200d Полная посадка", max_length=128, verbose_name="🙅\u200d Полная посадка"
            ),
        ),
    ]
