# Generated by Django 3.2.13 on 2022-06-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0022_auto_20220616_0953"),
    ]

    operations = [
        migrations.AddField(
            model_name="bottextsconfig",
            name="button_payment_free",
            field=models.CharField(default="", max_length=128, verbose_name=""),
        ),
        migrations.AddField(
            model_name="bottextsconfig",
            name="button_payment_pay",
            field=models.CharField(default="", max_length=128, verbose_name=""),
        ),
        migrations.AddField(
            model_name="bottextsconfig",
            name="button_payment_petrol",
            field=models.CharField(default="", max_length=128, verbose_name=""),
        ),
        migrations.AddField(
            model_name="bottextsconfig",
            name="new_trip_select_payment",
            field=models.TextField(default="Выбьерите тип оплаты", verbose_name="Выбьерите тип оплаты"),
        ),
    ]
