# Generated by Django 3.2.13 on 2022-06-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0023_auto_20220616_1037"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bottextsconfig",
            name="button_payment_free",
            field=models.CharField(default="🆓 Бесплатно", max_length=128, verbose_name="🆓 Бесплатно"),
        ),
        migrations.AlterField(
            model_name="bottextsconfig",
            name="button_payment_pay",
            field=models.CharField(default="💶 Платно", max_length=128, verbose_name="💶 Платно"),
        ),
        migrations.AlterField(
            model_name="bottextsconfig",
            name="button_payment_petrol",
            field=models.CharField(default="⛽️ Оплатить расходы", max_length=128, verbose_name="⛽️ Оплатить расходы"),
        ),
    ]
